[package]
name = "faulx"
version = "0.0.1"
description = "Rust implementation of killall"
keywords = ["killall"]
categories = ["command-line-utilities", "os"]
license.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["orx-parallel"]
rayon = ["dep:rayon"]
orx-parallel = ["dep:orx-parallel"]
regex = ["dep:regex"]

[dependencies]
clap.workspace = true
helpers = { path = "../helpers" }
humantime.workspace = true
nix.workspace = true
orx-parallel = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
