[package]
name = "procedre"
version = "0.0.1"
description = "Rust implementation of pstree"
keywords = ["pstree"]
categories = ["command-line-utilities", "os"]
license.workspace = true
rust-version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["orx-parallel"]
rayon = ["dep:rayon"]
orx-parallel = ["dep:orx-parallel"]

[dependencies]
clap.workspace = true
helpers = { path = "../helpers" }
orx-parallel = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
